import { Achievement } from '@/types/gamification';

export const ACHIEVEMENTS: Achievement[] = [
  // Habit Streaks
  {
    id: 'streak-3',
    title: 'Getting Started',
    description: 'Complete a habit 3 days in a row',
    icon: 'Flame',
    category: 'streak',
    condition: { type: 'streak', target: 3, metric: 'any_habit' },
    points: 50,
    rarity: 'common',
  },
  {
    id: 'streak-7',
    title: 'Week Warrior',
    description: 'Complete a habit 7 days in a row',
    icon: 'Trophy',
    category: 'streak',
    condition: { type: 'streak', target: 7, metric: 'any_habit' },
    points: 100,
    rarity: 'common',
  },
  {
    id: 'streak-14',
    title: 'Two Week Titan',
    description: 'Complete a habit 14 days in a row',
    icon: 'Award',
    category: 'streak',
    condition: { type: 'streak', target: 14, metric: 'any_habit' },
    points: 250,
    rarity: 'rare',
  },
  {
    id: 'streak-30',
    title: 'Monthly Master',
    description: 'Complete a habit 30 days in a row',
    icon: 'Medal',
    category: 'streak',
    condition: { type: 'streak', target: 30, metric: 'any_habit' },
    points: 500,
    rarity: 'epic',
  },

  // Sleep
  {
    id: 'sleep-consistent-7',
    title: 'Sleep Schedule Pro',
    description: 'Log sleep 7 days in a row',
    icon: 'Moon',
    category: 'sleep',
    condition: { type: 'consecutive', target: 7, metric: 'sleep_logs' },
    points: 100,
    rarity: 'common',
  },
  {
    id: 'sleep-quality-5',
    title: 'Sweet Dreams',
    description: 'Rate sleep quality 5/5 three times',
    icon: 'Star',
    category: 'sleep',
    condition: { type: 'total', target: 3, metric: 'perfect_sleep' },
    points: 75,
    rarity: 'rare',
  },
  {
    id: 'early-bird',
    title: 'Early Bird',
    description: 'Wake up before 7 AM five times',
    icon: 'Sunrise',
    category: 'sleep',
    condition: { type: 'total', target: 5, metric: 'early_wake' },
    points: 100,
    rarity: 'rare',
  },

  // Mood
  {
    id: 'mood-streak-7',
    title: 'Self-Aware',
    description: 'Log your mood 7 days in a row',
    icon: 'Heart',
    category: 'mood',
    condition: { type: 'consecutive', target: 7, metric: 'mood_logs' },
    points: 100,
    rarity: 'common',
  },
  {
    id: 'journal-10',
    title: 'Dear Diary',
    description: 'Write 10 journal entries',
    icon: 'BookHeart',
    category: 'mood',
    condition: { type: 'total', target: 10, metric: 'journal_entries' },
    points: 150,
    rarity: 'rare',
  },
  {
    id: 'happy-week',
    title: 'Happy Week',
    description: 'Average mood above 7 for a week',
    icon: 'Smile',
    category: 'mood',
    condition: { type: 'special', target: 1, metric: 'happy_week' },
    points: 200,
    rarity: 'epic',
  },

  // Habits
  {
    id: 'habits-5',
    title: 'Habit Builder',
    description: 'Track 5 different habits',
    icon: 'ListChecks',
    category: 'habits',
    condition: { type: 'total', target: 5, metric: 'active_habits' },
    points: 100,
    rarity: 'common',
  },
  {
    id: 'habits-complete-all',
    title: 'Perfect Day',
    description: 'Complete all habits in a single day',
    icon: 'Sparkles',
    category: 'habits',
    condition: { type: 'special', target: 1, metric: 'perfect_day' },
    points: 150,
    rarity: 'rare',
  },

  // Points Milestones
  {
    id: 'points-100',
    title: 'First Steps',
    description: 'Earn 100 points',
    icon: 'Zap',
    category: 'special',
    condition: { type: 'milestone', target: 100, metric: 'total_points' },
    points: 0,
    rarity: 'common',
  },
  {
    id: 'points-500',
    title: 'Getting Momentum',
    description: 'Earn 500 points',
    icon: 'Rocket',
    category: 'special',
    condition: { type: 'milestone', target: 500, metric: 'total_points' },
    points: 0,
    rarity: 'common',
  },
  {
    id: 'points-1000',
    title: 'Rising Star',
    description: 'Earn 1,000 points',
    icon: 'Star',
    category: 'special',
    condition: { type: 'milestone', target: 1000, metric: 'total_points' },
    points: 0,
    rarity: 'rare',
  },
  {
    id: 'points-5000',
    title: 'Wellness Warrior',
    description: 'Earn 5,000 points',
    icon: 'Shield',
    category: 'special',
    condition: { type: 'milestone', target: 5000, metric: 'total_points' },
    points: 0,
    rarity: 'epic',
  },
  {
    id: 'points-10000',
    title: 'Wellness Champion',
    description: 'Earn 10,000 points',
    icon: 'Crown',
    category: 'special',
    condition: { type: 'milestone', target: 10000, metric: 'total_points' },
    points: 0,
    rarity: 'legendary',
  },
];

export const WEEKLY_CHALLENGES = [
  {
    id: 'complete-habits-20',
    title: 'Habit Hero',
    description: 'Complete 20 habit check-ins this week',
    targetValue: 20,
    reward: 100,
  },
  {
    id: 'log-sleep-7',
    title: 'Sleep Tracker',
    description: 'Log your sleep every day this week',
    targetValue: 7,
    reward: 75,
  },
  {
    id: 'log-mood-7',
    title: 'Mood Monitor',
    description: 'Log your mood every day this week',
    targetValue: 7,
    reward: 75,
  },
  {
    id: 'journal-3',
    title: 'Reflective Writer',
    description: 'Write 3 journal entries this week',
    targetValue: 3,
    reward: 50,
  },
  {
    id: 'water-50',
    title: 'Hydration Station',
    description: 'Log 50 glasses of water this week',
    targetValue: 50,
    reward: 100,
  },
];
