import { Habit } from '@/types/habit';

export const PREBUILT_HABITS: Omit<Habit, 'id' | 'createdAt' | 'order'>[] = [
  {
    name: 'Drink 8 glasses of water',
    description: 'Stay hydrated throughout the day',
    icon: 'Droplets',
    color: '#3B82F6',
    frequency: 'daily',
    targetCount: 8,
    category: 'wellness',
    isPrebuilt: true,
    pointsPerCompletion: 10,
    active: false,
  },
  {
    name: 'Take vitamins',
    description: 'Daily vitamin supplement',
    icon: 'Pill',
    color: '#10B981',
    frequency: 'daily',
    category: 'health',
    isPrebuilt: true,
    pointsPerCompletion: 5,
    active: false,
  },
  {
    name: 'Exercise 30 minutes',
    description: 'Any form of physical activity',
    icon: 'Dumbbell',
    color: '#EF4444',
    frequency: 'daily',
    category: 'health',
    isPrebuilt: true,
    pointsPerCompletion: 20,
    active: false,
  },
  {
    name: 'Meditate',
    description: '5-10 minutes of mindfulness',
    icon: 'Brain',
    color: '#8B5CF6',
    frequency: 'daily',
    category: 'wellness',
    isPrebuilt: true,
    pointsPerCompletion: 15,
    active: false,
  },
  {
    name: 'Read for pleasure',
    description: '20 minutes of non-academic reading',
    icon: 'BookOpen',
    color: '#F59E0B',
    frequency: 'daily',
    category: 'wellness',
    isPrebuilt: true,
    pointsPerCompletion: 10,
    active: false,
  },
  {
    name: 'No phone before bed',
    description: 'Avoid screens 30 min before sleep',
    icon: 'SmartphoneOff',
    color: '#6366F1',
    frequency: 'daily',
    category: 'health',
    isPrebuilt: true,
    pointsPerCompletion: 15,
    active: false,
  },
  {
    name: 'Stretch / Yoga',
    description: '10 minutes of stretching',
    icon: 'Flower2',
    color: '#EC4899',
    frequency: 'daily',
    category: 'health',
    isPrebuilt: true,
    pointsPerCompletion: 10,
    active: false,
  },
  {
    name: 'Connect with a friend',
    description: 'Call, text, or meet a friend',
    icon: 'Users',
    color: '#14B8A6',
    frequency: 'daily',
    category: 'social',
    isPrebuilt: true,
    pointsPerCompletion: 15,
    active: false,
  },
  {
    name: 'Review tomorrow\'s schedule',
    description: 'Plan your next day before bed',
    icon: 'CalendarCheck',
    color: '#0EA5E9',
    frequency: 'daily',
    category: 'productivity',
    isPrebuilt: true,
    pointsPerCompletion: 10,
    active: false,
  },
  {
    name: 'Inbox zero',
    description: 'Process all emails',
    icon: 'Mail',
    color: '#64748B',
    frequency: 'daily',
    category: 'productivity',
    isPrebuilt: true,
    pointsPerCompletion: 10,
    active: false,
  },
  {
    name: 'Eat a healthy breakfast',
    description: 'Start your day with nutrition',
    icon: 'Apple',
    color: '#22C55E',
    frequency: 'daily',
    category: 'health',
    isPrebuilt: true,
    pointsPerCompletion: 10,
    active: false,
  },
  {
    name: 'Practice gratitude',
    description: 'Write 3 things you\'re grateful for',
    icon: 'Heart',
    color: '#F43F5E',
    frequency: 'daily',
    category: 'wellness',
    isPrebuilt: true,
    pointsPerCompletion: 10,
    active: false,
  },
];
